<?php
/**
 * @file
 * Code for the TGD Base feature.
 */

include_once 'tgd_base.features.inc';

/**
 * Implements hook_menu().
 */
function tgd_base_menu() {
  // Menu items that are basically just menu blocks.
  $items['admin/config/tgd'] = array(
    'title' => 'The Good Data',
    'description' => 'Configure TGD Social',
    'position' => 'right',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  return $items;
}