<?php
/**
 * @file
 * Code for the TGD Base feature.
 */

include_once 'tgd_base.features.inc';

/**
 * Implements hook_menu().
 */
function tgd_base_menu() {
  // Menu items that are basically just menu blocks.
  $items['admin/config/tgd'] = array(
    'title' => 'The Good Data',
    'description' => 'Configure TGD Social',
    'position' => 'right',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/tgd/settings'] = array(
    'title' => 'Mixed options',
    'description' => 'Configure TGD',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('variable_group_form', 'tgd'),
    'access arguments' => array('administer site configuration'),
    'weight' => -10,
  );
  return $items;
}

/**
 * Get group id (space) from node.
 */
function tgd_base_node_get_gid($node) {
	return !empty($node->{OG_AUDIENCE_FIELD}) ? $node->{OG_AUDIENCE_FIELD}[LANGUAGE_NONE][0]['target_id'] : 0;
}